services:
  - type: web
    name: gestion-olimpistas
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://gestion-olimpiadas.onrender.com
      - key: DB_CONNECTION
        value: pgsql
